export const CHANNELS = {
  FILTER_OPTIONS: 'FILTER_OPTIONS',
  ABNORMALITY_FILTER_OPTIONS: 'ABNORMALITY_FILTER_OPTIONS',
  PATIENT_IDS: 'PATIENT_IDS',
  PATIENTS: 'PATIENTS',
  PATIENT_DETAILS: 'PATIENT_DETAILS',
  PATIENT_IMAGES_DETAILS: 'PATIENT_IMAGES_DETAILS',
  FILTER_PATIENTS: 'FILTER_PATIENTS',
  PATIENT_IMAGE: 'PATIENT_IMAGE',
  SAVE_QUERY: 'SAVE_QUERY',
  LOAD_QUERIES: 'LOAD_QUERIES',
  DELETE_QUERY: 'DELETE_QUERY',
  CLOSE_WINDOW: 'CLOSE_WINDOW',
};
